### ISSUE TITLE
GetFormula is finding an index out of bounds at line 1101 on MainForm.cs

### ISSUE THREAD

**Issue by roku674** [roku674/StarportExcel#2]
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=mscorlib
  StackTrace:
   at System.String.get_Chars(Int32 index)
   at StarportExcel.MainForm.GetFormula(String planetName) in C:\Users\ZANDER\source\repos\StarportExcel\Starport\MainForm.cs:line 1101
   at StarportExcel.MainForm.FindZounds_Click(Object sender, EventArgs e) in C:\Users\ZANDER\source\repos\StarportExcel\Starport\MainForm.cs:line 690
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at StarportExcel.Program.Main() in C:\Users\ZANDER\source\repos\StarportExcel\Starport\Program.cs:line 19

**Comment by roku674** [comment]
problem with ordering if statement, solved
